project:
  type: website
  output-dir: docs
  render:
    - index.qmd
    - about.qmd
    - "posts/*.qmd"

website:
  title: "Best Idea Wins"
  open-graph: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  page-footer: 
    left: "Copyright 2026, Christon Hill" 
    right: 
      - icon: twitter 
        href: https://twitter.com/
      - icon: linkedin
        href: https://www.linkedin.com/in/christon-hill/

format:
  html:
    theme:
      - sandstone  
      - brand
    css: styles.css
    toc: true
    title-block-banner: true
    title-block-style: default
    respect-user-color-scheme: true
    csl: assets/cell.csl
